# Generated by Django 4.2.20 on 2025-05-02 09:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("state", models.TextField(blank=True, max_length=20, null=True)),
                ("district", models.TextField(blank=True, max_length=30, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("pincode", models.BigIntegerField(blank=True, null=True)),
                ("contact_no", models.BigIntegerField(blank=True, null=True)),
                ("mobile", models.BigIntegerField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Full website URL including https://",
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("category", models.TextField(blank=True, null=True)),
                ("blood_component_available", models.TextField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BloodDonationCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="BloodDonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(65),
                        ]
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{10,15}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("address", models.TextField()),
                ("units_donated", models.PositiveIntegerField(default=0)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("medical_history", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "osm_id",
                    models.BigIntegerField(
                        blank=True, help_text="OpenStreetMap ID", null=True, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hospital_type",
                    models.CharField(
                        choices=[
                            ("general", "General Hospital"),
                            ("specialty", "Specialty Hospital"),
                            ("teaching", "Teaching Hospital"),
                            ("clinic", "Clinic"),
                            ("government", "Government Hospital"),
                            ("private", "Private Hospital"),
                        ],
                        default="general",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Include country code if available",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Full website URL including https://",
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Hospitals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("blood_group", models.CharField(max_length=5)),
                ("quantity_ml", models.PositiveIntegerField()),
                (
                    "blood_bank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bloodbankapp.bloodbank",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bloodbankapp.blooddonor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_group", models.CharField(max_length=5)),
                ("quantity_ml", models.PositiveIntegerField()),
                ("request_date", models.DateField(auto_now_add=True)),
                (
                    "required_by",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 5, 5, 9, 14, 54, 829045, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("urgent", "Urgent"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Fulfilled", "Fulfilled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bloodbankapp.bloodbank",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bloodbankapp.hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("organizer", models.CharField(max_length=150)),
                (
                    "contact_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{10,15}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "donors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="camps_attended",
                        to="bloodbankapp.blooddonor",
                    ),
                ),
            ],
        ),
    ]
