# Generated by Django 5.1.7 on 2025-03-28 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodcamp",
            name="donors",
            field=models.ManyToManyField(
                blank=True, related_name="camps_attended", to="bloodbankapp.blooddonor"
            ),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="bloodcamp",
            name="contact_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?\\d{10,15}$", "Enter a valid phone number"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(65),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="contact_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?\\d{10,15}$", "Enter a valid phone number"
                    )
                ],
            ),
        ),
    ]
