# Generated by Django 4.2.20 on 2025-05-02 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 5, 9, 15, 42, 906134, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
