# Generated by Django 4.2.20 on 2025-05-03 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bloodbankapp", "0003_alter_bloodrequest_required_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospital",
            options={},
        ),
        migrations.RemoveField(
            model_name="bloodbank",
            name="contact_no",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="fulfilled_by",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="quantity_ml",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="required_by",
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="blood_type",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="contact_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="fulfilled",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="requester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="units",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="hospital",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="request_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="hospital",
            constraint=models.UniqueConstraint(
                fields=("name", "address"), name="unique_hospital_name_address"
            ),
        ),
    ]
