# Generated by Django 4.2.20 on 2025-04-19 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0004_donation_bloodrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="blooddonor",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="O",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="blooddonor",
            name="medical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 22, 18, 37, 23, 523533, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("urgent", "Urgent"),
                    ("critical", "Critical"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
    ]
