# Generated by Django 4.2.20 on 2025-05-04 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bloodbankapp", "0005_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="bloodcamp",
            name="date",
        ),
        migrations.RemoveField(
            model_name="bloodcamp",
            name="description",
        ),
        migrations.RemoveField(
            model_name="bloodcamp",
            name="location",
        ),
        migrations.RemoveField(
            model_name="bloodcamp",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="bloodcamp",
            name="time",
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="camp_type",
            field=models.CharField(
                choices=[
                    ("donation", "Blood Donation Camp"),
                    ("awareness", "Awareness Program"),
                    ("mixed", "Mixed Event"),
                ],
                default="donation",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bloodcamp",
            name="contact_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="bloodcamp",
            name="donors",
            field=models.ManyToManyField(
                blank=True, null=True, to="bloodbankapp.blooddonor"
            ),
        ),
        migrations.AlterField(
            model_name="bloodcamp",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bloodcamp",
            name="organizer",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="DonationOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_type", models.CharField(max_length=3)),
                ("available_date", models.DateField()),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("matched", "Matched"),
                            ("donated", "Donated"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
                ("can_travel", models.BooleanField(default=False)),
                ("max_travel_distance", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bloodbankapp.city",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodDonationMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "donation_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bloodbankapp.donationoffer",
                    ),
                ),
                (
                    "matched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bloodbankapp.bloodrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bloodcamp",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bloodbankapp.city",
            ),
        ),
        migrations.CreateModel(
            name="CampRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("attended", models.BooleanField(default=False)),
                ("donation_made", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bloodbankapp.bloodcamp",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bloodbankapp.blooddonor",
                    ),
                ),
            ],
            options={
                "unique_together": {("donor", "camp")},
            },
        ),
    ]
