# Generated by Django 4.2.20 on 2025-04-19 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0005_blooddonor_gender_blooddonor_medical_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 22, 18, 37, 58, 510936, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
