# Generated by Django 4.2.20 on 2025-04-19 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0006_alter_bloodrequest_required_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 22, 18, 38, 41, 55816, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
