# Generated by Django 4.2.20 on 2025-05-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0006_city_remove_bloodcamp_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="can_accept_from_other_cities",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bloodbankapp.city",
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="patient_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="units_required",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
