# Generated by Django 4.2.20 on 2025-04-21 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0007_alter_bloodrequest_required_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 24, 11, 59, 28, 777281, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
