# Generated by Django 4.2.20 on 2025-05-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0007_bloodrequest_can_accept_from_other_cities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(blank=True, null=True),
        ),
    ]
