# Generated by Django 4.2.20 on 2025-04-24 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0008_alter_bloodrequest_required_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 27, 6, 43, 13, 85993, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
