# Generated by Django 4.2.20 on 2025-05-06 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0008_bloodrequest_required_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blooddonationcamp",
            name="address",
        ),
        migrations.RemoveField(
            model_name="blooddonationcamp",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="blooddonationcamp",
            name="longitude",
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="contact_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="contact_phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="expected_donors",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="is_approved",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="location",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="organizer",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="blooddonationcamp",
            name="start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="blooddonationcamp",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="blooddonationcamp",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
