# Generated by Django 4.2.20 on 2025-04-24 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0009_alter_bloodrequest_required_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 27, 9, 36, 57, 933044, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
