# Generated by Django 4.2.20 on 2025-04-25 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0010_alter_bloodrequest_required_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 28, 5, 34, 27, 127887, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
