# Generated by Django 4.2.20 on 2025-04-29 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0011_alter_bloodrequest_required_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("Govt", "Government"),
                            ("NGO", "NGO"),
                            ("Private", "Private"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("organization_name", models.CharField(max_length=100)),
                ("organizer_name", models.CharField(max_length=100)),
                ("organizer_mobile", models.CharField(max_length=15)),
                ("organizer_email", models.EmailField(max_length=254)),
                (
                    "co_organizer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "co_organizer_mobile",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("camp_name", models.CharField(max_length=100)),
                ("camp_address", models.TextField()),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("city_name", models.CharField(max_length=100)),
                ("blood_bank", models.CharField(max_length=100)),
                ("camp_propose_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("estimated_participants", models.PositiveIntegerField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "reference_or_supporter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 2, 16, 59, 23, 569352, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bloodbankapp.state",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bloodbank",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bloodbankapp.district",
            ),
        ),
    ]
