# Generated by Django 5.2 on 2025-05-01 17:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0011_alter_bloodrequest_required_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('primary_season', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('Monsoon', 'Monsoon'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], max_length=50)),
                ('blood_types_affected', models.CharField(help_text='Comma-separated blood types most needed', max_length=200)),
                ('avg_blood_requirement_ml', models.PositiveIntegerField(help_text='Average blood requirement per case in mL')),
            ],
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='required_by',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 17, 28, 15, 109760, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SeasonalDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('season', models.CharField(max_length=50)),
                ('predicted_demand_increase', models.FloatField(help_text='Percentage increase in demand')),
                ('actual_demand_increase', models.FloatField(blank=True, null=True)),
                ('predicted_blood_types', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbankapp.disease')),
            ],
        ),
    ]
