# Generated by Django 4.2.20 on 2025-04-30 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0012_campregistration_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodDonationCamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="CampRegistration",
        ),
        migrations.RemoveField(
            model_name="bloodbank",
            name="district",
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 3, 19, 23, 38, 207516, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
