# Generated by Django 4.2.20 on 2025-05-07 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bloodbankapp", "0012_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="crosscitydonation",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cross_city_donations",
                to="bloodbankapp.patient",
            ),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cross_city_donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="donor_blood_bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor_blood_bank",
                to="bloodbankapp.bloodbank",
            ),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="donor_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor_city",
                to="bloodbankapp.city",
            ),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="patient_blood_bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_blood_bank",
                to="bloodbankapp.bloodbank",
            ),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="patient_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_city",
                to="bloodbankapp.city",
            ),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiated", "Initiated"),
                    ("donated", "Donated"),
                    ("transferred", "Transferred"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="initiated",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="units",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crosscitydonation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
