# Generated by Django 4.2.20 on 2025-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0013_crosscitydonation_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crosscitydonation",
            name="state_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
