# Generated by Django 4.2.20 on 2025-04-30 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0013_blooddonationcamp_delete_campregistration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodbank",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodbank",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 3, 19, 26, 9, 419562, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
