# Generated by Django 4.2.20 on 2025-04-30 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0014_bloodbank_latitude_bloodbank_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 3, 19, 26, 47, 391868, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
