# Generated by Django 4.2.20 on 2025-05-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0014_crosscitydonation_state_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blooddonor",
            name="donor_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
