# Generated by Django 4.2.20 on 2025-04-30 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0015_alter_bloodrequest_required_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospital",
            options={
                "ordering": ["name"],
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitals",
            },
        ),
        migrations.AddField(
            model_name="hospital",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="hospital_type",
            field=models.CharField(default="general", max_length=50),
        ),
        migrations.AddField(
            model_name="hospital",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="osm_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 3, 20, 7, 51, 998264, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
