# Generated by Django 4.2.20 on 2025-05-09 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0015_blooddonor_donor_city_alter_blooddonor_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bloodbankapp.city",
            ),
        ),
    ]
