# Generated by Django 4.2.20 on 2025-04-30 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0016_alter_hospital_options_hospital_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospital",
            old_name="contact_number",
            new_name="phone",
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 3, 20, 17, 12, 764695, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
