# Generated by Django 4.2.20 on 2025-05-09 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0016_userprofile_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodbank",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bloodbankapp.city",
            ),
        ),
    ]
