# Generated by Django 4.2.20 on 2025-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0017_bloodbank_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
