# Generated by Django 4.2.20 on 2025-05-01 12:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0017_rename_contact_number_hospital_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospital",
            options={"ordering": ["name"], "verbose_name_plural": "Hospitals"},
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="location",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="phone",
        ),
        migrations.AddField(
            model_name="hospital",
            name="district",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="pincode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Include country code if available",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Full website URL including https://",
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 4, 12, 40, 4, 529741, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="hospital_type",
            field=models.CharField(
                choices=[
                    ("general", "General Hospital"),
                    ("specialty", "Specialty Hospital"),
                    ("teaching", "Teaching Hospital"),
                    ("clinic", "Clinic"),
                    ("government", "Government Hospital"),
                    ("private", "Private Hospital"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="osm_id",
            field=models.BigIntegerField(
                blank=True, help_text="OpenStreetMap ID", null=True, unique=True
            ),
        ),
    ]
