# Generated by Django 4.2.20 on 2025-05-01 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bloodbankapp",
            "0018_alter_hospital_options_remove_hospital_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 4, 13, 14, 17, 946504, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
