# Generated by Django 4.2.20 on 2025-05-01 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0019_alter_bloodrequest_required_by_alter_hospital_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 4, 13, 15, 10, 36149, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="hospital_type",
            field=models.CharField(
                choices=[
                    ("general", "General Hospital"),
                    ("specialty", "Specialty Hospital"),
                    ("teaching", "Teaching Hospital"),
                    ("clinic", "Clinic"),
                    ("government", "Government Hospital"),
                    ("private", "Private Hospital"),
                ],
                default="general",
                max_length=50,
                null=True,
            ),
        ),
    ]
