# Generated by Django 4.2.20 on 2025-05-01 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0020_alter_bloodrequest_required_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 4, 16, 24, 51, 89711, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
