# Generated by Django 4.2.20 on 2025-05-01 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0021_alter_bloodrequest_required_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospital",
            old_name="telephone",
            new_name="phone",
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 4, 16, 36, 29, 700496, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
