# Generated by Django 4.2.20 on 2025-05-01 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbankapp", "0022_rename_telephone_hospital_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodbank",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 4, 16, 42, 57, 748657, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Include country code if available",
                max_length=30,
                null=True,
            ),
        ),
    ]
