# Generated by Django 4.2.20 on 2025-05-01 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bloodbankapp",
            "0023_alter_bloodbank_name_alter_bloodrequest_required_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="required_by",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 4, 16, 43, 37, 174387, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
