# Generated by Django 5.2 on 2025-05-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0012_blooddonationcamp_disease_and_more'),
        ('bloodbankapp', '0024_alter_bloodrequest_required_by_and_more'),
    ]

    operations = [
    ]
