# Generated by Django 5.2 on 2025-05-02 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0025_merge_20250501_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonaldemand',
            name='disease',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='required_by',
            field=models.DateField(default=datetime.datetime(2025, 5, 5, 16, 48, 16, 770669, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='SeasonalDemand',
        ),
    ]
