# Generated by Django 5.2 on 2025-05-04 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0026_remove_seasonaldemand_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='required_by',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 10, 56, 43, 617770, tzinfo=datetime.timezone.utc)),
        ),
    ]
