# Generated by Django 5.2 on 2025-05-04 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0027_alter_bloodrequest_required_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='required_by',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 11, 0, 2, 214801, tzinfo=datetime.timezone.utc)),
        ),
    ]
