# Generated by Django 5.2 on 2025-05-04 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0028_alter_bloodrequest_required_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='required_by',
            field=models.DateField(default=datetime.datetime(2025, 5, 7, 12, 24, 7, 250357, tzinfo=datetime.timezone.utc)),
        ),
    ]
